### ISSUE TITLE
shift-click in webkit browsers causes crash when svg text is present

### ISSUE THREAD

**Issue by cjrd** [cjrd/directed-graph-creator#1]
webkit bug: https://bugs.webkit.org/show_bug.cgi?id=114745

**Comment by cjrd** [comment]
Removing text selection via a CSS rule seems to have fixed the problem.

CSS rule taken from [this stackoverflow post](http://stackoverflow.com/questions/826782/css-rule-to-disable-text-selection-highlighting):

``` css
g{
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
};
```
